server:
  port: 10000

#sidecar:
#  prot: 8000

endpoints:
  restart:
    enable: true
  shutdown:
    enable: true
  health:
    sensitive: false

zuul:
  ignored-services: "*"
  routes:
    product:
      path: /product/**
      url: http://localhost:9001/product
    recommend:
      path: /recommend/**
      url: http://localhost:9002/recommend
    review:
      path: /review/**
      url: http://localhost:9001/review