server:
  port: ${PORT:${SERVER_PORT:0}}

eureka:
  instance:
    instanceId: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/

#words: 你好,我好,大家好