spring:
  application:
    name: config-client1
  cloud:
    config:
      uri: http://localhost:8886
      name: test-cfg2
      profile: dev

server:
  port: 8085

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/